# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:21
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Africa/Lagos'),
        ),
    ]
